# Generated by Django 3.1.5 on 2021-01-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('name', models.CharField(max_length=100, verbose_name='Instrutor')),
                ('age', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[(None, 'Escolha seu Gênero'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10, verbose_name='Gênero')),
                ('services', models.TextField(verbose_name='Acompanhamento')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
            },
        ),
    ]
