# Generated by Django 3.1.5 on 2021-01-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('members', '0002_remove_member_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='instructor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='instructors.instructor', verbose_name='Instrutor'),
            preserve_default=False,
        ),
    ]
